# File: .github/workflows/repo-sync.yml
name: task_name # 任务名称
on:
  schedule:
    - cron: 'cron表达式' # 执行时间
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ main ] #  当前仓库的该 .yml 文件存放的分支的名称
  repository_dispatch:
    types: sync-scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: task_name # 运行过程中的名称
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          # 你要克隆对方仓库的 git 地址
          source_repo: "git_address" 
          # 克隆对方仓库中分支的名称
          source_branch: "master"
          # 在当前仓库新建一个你自己的远程分支
          # 如果自己仓库中已经有这个名称的分支，则会拉取后覆盖在这条分支里面
          destination_branch: "task_name" 
          github_token: ${{ secrets.PAT }}
