name: Task_Name # Task name

on:
  schedule:
    - cron: 'Cron_expression' # Execution time
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync-scripts
    
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Task_Name # Task name
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "Git_Address" # Git address of this repository
          source_branch: "Git_Branch" # Branch of this repository
          destination_branch: "Your_Branch" # Create your own branch
          github_token: ${{ secrets.PAT }}
